// <auto-generated />
using AdmirMuhicAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdmirMuhicAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523171032_AddProjectsSeed")]
    partial class AddProjectsSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdmirMuhicAPI.Models.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GeneralInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Home");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GeneralInfo = "Fullstack-utvecklare med fokus på .NET-ekosystemet och moderna frontend-ramverk. Erfarenhet av att bygga allt från komplexa intranät för offentlig sektor till kundanpassade affärssystem."
                        });
                });

            modelBuilder.Entity("AdmirMuhicAPI.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hemsida för Olofströms IK, utvecklad i Wordpress. Projektet fokuserade på att skapa en användarvänlig plattform för supportrar och medlemmar.",
                            Image = "https://iili.io/BmNG5Cb.png",
                            Link = "https://www.oik.se",
                            Tags = "Wordpress",
                            Title = "Olofströms Ishockeyklubb"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lorem iåpsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
                            Image = "https://wearereeds.co.uk/assets/images/transforms/Insights/_1920x900_crop_center-center_none/35873/lorem-ipsum.avif",
                            Link = "https://www.lipsum.com/",
                            Tags = ".NET,Vue.js,SQL,Bootstrap",
                            Title = "Lorem ipsum dolor sit amet"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
